---
- name: post setup sanity check 
  hosts:
    - name: check tang server
        check and register/output 
        #need to ansiblize the following cmd
        #ssh <tang server> sudo systemctl status tangd.socket
    - name: check clevis clients
      check and register/output
      # need to ansibllize 
      # ssh <client> sudo clevis luks list -d /dev/vda2
      # loop and register response 
#ansible.builtin.service_facts module – Return service state information as fact data 
#or
#ansible.builtin.systemd module – Manage systemd units
